# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nowifi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wifi(object):
    def setupUi(self, wifi):
        wifi.setObjectName("wifi")
        wifi.resize(455, 202)
        wifi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(wifi)
        self.label.setGeometry(QtCore.QRect(60, 10, 311, 71))
        self.label.setStyleSheet("font: 18pt \"Ubuntu\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(wifi)
        self.label_2.setGeometry(QtCore.QRect(180, 80, 101, 101))
        self.label_2.setStyleSheet("background-image: url(:/images/nowifi.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(wifi)
        QtCore.QMetaObject.connectSlotsByName(wifi)

    def retranslateUi(self, wifi):
        _translate = QtCore.QCoreApplication.translate
        wifi.setWindowTitle(_translate("wifi", "قطع ارتباط"))
        self.label.setText(_translate("wifi", "اتصال به اینترنت برقرار نیست"))
import ui.icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wifi = QtWidgets.QDialog()
    ui = Ui_wifi()
    ui.setupUi(wifi)
    wifi.show()
    sys.exit(app.exec_())
